// 球队中文简称 —— 纯前端展示层的翻译表，不改变任何存储/接口数据。
// 后端队名（match.team1/team2 等）保持原样不动，仅在渲染时做替换；
// 找不到的队伍原样显示英文名，不是 bug，是覆盖范围的自然边界。
// 数据来源：backend 当前 6 个已接入赛事（2026世界杯/英超/西甲/意甲/德甲/欧冠）
// 里出现过的全部 156 支球队，2026-08 抓取，一一对应生成。
export const TEAM_ZH = {
  "1. FC Heidenheim 1846": "海登海姆",
  "1. FC Köln": "科隆",
  "1. FC Union Berlin": "柏林联合",
  "1. FSV Mainz 05": "美因茨",
  "AC Milan": "AC米兰",
  "AC Monza": "蒙扎",
  "AC Pisa 1909": "比萨",
  "AC Sparta Praha": "布拉格斯巴达",
  "ACF Fiorentina": "佛罗伦萨",
  "AFC Bournemouth": "伯恩茅斯",
  "AS Monaco": "摩纳哥",
  "AS Roma": "罗马",
  "Algeria": "阿尔及利亚",
  "Argentina": "阿根廷",
  "Arsenal": "阿森纳",
  "Aston Villa": "阿斯顿维拉",
  "Atalanta BC": "亚特兰大",
  "Athletic Club": "毕尔巴鄂竞技",
  "Australia": "澳大利亚",
  "Austria": "奥地利",
  "BSC Young Boys": "伯尔尼年轻人",
  "Bayer 04 Leverkusen": "勒沃库森",
  "Belgium": "比利时",
  "Bologna FC 1909": "博洛尼亚",
  "Borussia Dortmund": "多特蒙德",
  "Borussia Mönchengladbach": "门兴格拉德巴赫",
  "Bosnia & Herzegovina": "波黑",
  "Brazil": "巴西",
  "Brentford": "布伦特福德",
  "Brighton & Hove Albion": "布莱顿",
  "Burnley": "伯恩利",
  "CA Osasuna": "奥萨苏纳",
  "Cagliari Calcio": "卡利亚里",
  "Canada": "加拿大",
  "Cape Verde": "佛得角",
  "Celtic": "凯尔特人",
  "Chelsea": "切尔西",
  "Club Atlético de Madrid": "马德里竞技",
  "Club Brugge KV": "布鲁日",
  "Colombia": "哥伦比亚",
  "Como 1907": "科莫",
  "Coventry City": "考文垂",
  "Croatia": "克罗地亚",
  "Crystal Palace": "水晶宫",
  "Curaçao": "库拉索",
  "Czech Republic": "捷克",
  "DR Congo": "刚果(金)",
  "Deportivo Alavés": "阿拉维斯",
  "Ecuador": "厄瓜多尔",
  "Egypt": "埃及",
  "Eintracht Frankfurt": "法兰克福",
  "Elche CF": "埃尔切",
  "England": "英格兰",
  "Everton": "埃弗顿",
  "FC Augsburg": "奥格斯堡",
  "FC Barcelona": "巴塞罗那",
  "FC Bayern München": "拜仁慕尼黑",
  "FC Internazionale Milano": "国际米兰",
  "FC Red Bull Salzburg": "萨尔茨堡红牛",
  "FC Schalke 04": "沙尔克04",
  "FC St. Pauli 1910": "圣保利",
  "FK Crvena Zvezda": "贝尔格莱德红星",
  "FK Shakhtar Donetsk": "顿涅茨克矿工",
  "Feyenoord Rotterdam": "费耶诺德",
  "France": "法国",
  "Frosinone Calcio": "弗罗西诺内",
  "Fulham": "富勒姆",
  "GNK Dinamo Zagreb": "萨格勒布迪那摩",
  "Genoa CFC": "热那亚",
  "Germany": "德国",
  "Getafe CF": "赫塔菲",
  "Ghana": "加纳",
  "Girona": "赫罗纳",
  "Haiti": "海地",
  "Hamburger SV": "汉堡",
  "Hellas Verona": "维罗纳",
  "Hull City": "赫尔城",
  "Ipswich Town": "伊普斯维奇",
  "Iran": "伊朗",
  "Iraq": "伊拉克",
  "Ivory Coast": "科特迪瓦",
  "Japan": "日本",
  "Jordan": "约旦",
  "Juventus": "尤文图斯",
  "Leeds United": "利兹联",
  "Levante UD": "莱万特",
  "Lille OSC": "里尔",
  "Liverpool": "利物浦",
  "Manchester City": "曼城",
  "Manchester United": "曼联",
  "Mexico": "墨西哥",
  "Morocco": "摩洛哥",
  "Málaga CF": "马拉加",
  "Netherlands": "荷兰",
  "New Zealand": "新西兰",
  "Newcastle United": "纽卡斯尔联",
  "Norway": "挪威",
  "Nottingham Forest": "诺丁汉森林",
  "PSV": "埃因霍温",
  "Panama": "巴拿马",
  "Paraguay": "巴拉圭",
  "Paris Saint-Germain": "巴黎圣日耳曼",
  "Parma Calcio 1913": "帕尔马",
  "Portugal": "葡萄牙",
  "Qatar": "卡塔尔",
  "RB Leipzig": "莱比锡红牛",
  "RC Celta de Vigo": "塞尔塔",
  "RC Deportivo La Coruña": "拉科鲁尼亚",
  "RCD Espanyol de Barcelona": "西班牙人",
  "RCD Mallorca": "马略卡",
  "Rayo Vallecano de Madrid": "巴列卡诺",
  "Real Betis Balompié": "皇家贝蒂斯",
  "Real Madrid CF": "皇家马德里",
  "Real Oviedo": "皇家奥维耶多",
  "Real Racing Club de Santander": "桑坦德竞技",
  "Real Sociedad de Fútbol": "皇家社会",
  "SC Freiburg": "弗赖堡",
  "SC Paderborn 07": "帕德博恩",
  "SK Sturm Graz": "格拉茨风暴",
  "SS Lazio": "拉齐奥",
  "SSC Napoli": "那不勒斯",
  "SV 07 Elversberg": "埃尔沃斯贝格",
  "SV Werder Bremen": "云达不来梅",
  "Saudi Arabia": "沙特阿拉伯",
  "Scotland": "苏格兰",
  "Senegal": "塞内加尔",
  "Sevilla": "塞维利亚",
  "South Africa": "南非",
  "South Korea": "韩国",
  "Spain": "西班牙",
  "Sport Lisboa e Benfica": "本菲卡",
  "Sporting Clube de Portugal": "葡萄牙体育",
  "Stade Brestois 29": "布雷斯特",
  "Sunderland": "桑德兰",
  "Sweden": "瑞典",
  "Switzerland": "瑞士",
  "TSG 1899 Hoffenheim": "霍芬海姆",
  "Torino": "都灵",
  "Tottenham Hotspur": "热刺",
  "Tunisia": "突尼斯",
  "Turkey": "土耳其",
  "US Cremonese": "克雷莫纳",
  "US Lecce": "莱切",
  "US Sassuolo Calcio": "萨索洛",
  "USA": "美国",
  "Udinese Calcio": "乌迪内斯",
  "Uruguay": "乌拉圭",
  "Uzbekistan": "乌兹别克斯坦",
  "Valencia CF": "瓦伦西亚",
  "Venezia": "威尼斯",
  "VfB Stuttgart": "斯图加特",
  "VfL Wolfsburg": "沃尔夫斯堡",
  "Villarreal CF": "比利亚雷亚尔",
  "West Ham United": "西汉姆联",
  "Wolverhampton Wanderers": "狼队",
  "ŠK Slovan Bratislava": "布拉迪斯拉发斯拉万",
};

export const zhTeam = (name) => TEAM_ZH[name] || name;
